# Generated by Django 3.1.3 on 2020-11-23 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather_station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pressure',
            field=models.FloatField(),
        ),
    ]
