# Generated by Django 3.1.3 on 2020-12-02 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20201201_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_mean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_mean', models.FloatField()),
                ('pressure_mean', models.FloatField()),
                ('humidity_mean', models.FloatField()),
                ('date_mean', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
